### ISSUE TITLE
Testes não funcionam

### ISSUE THREAD

**Issue by cassiobotaro** [rochacbruno/wtf#1]
Fui rodar os testes e recebi o seguinte traceback:

Traceback (most recent call last):
  File "test_basic.py", line 4, in <module>
    from wtf.news_app import create_app
ImportError: No module named wtf.news_app

**Comment by rochacbruno** [comment]
``` bash
rochacbruno@~/www/wtf [almost_perfect] $ nosetests tests/
.
----------------------------------------------------------------------
Ran 1 test in 3.329s

OK
```

**Comment by rochacbruno** [comment]
Fixed in 818152d61a359b1a8344072a45c7dba339c6ca0a

**Comment by rochacbruno** [comment]
added `make test`

**Comment by cassiobotaro** [comment]
Desculpa abrir esta issue, mas descobri qual e o problema que deu aqui ao utilizar py.test e como solucionar.
Utilizando `py.test` dentro do virtualenv wrapper há uma confusão com pythonpath e a solução é simplesmente o comando:
add2virtualenv .

Outra solução é a seguinte, rode os testes da seguinte maneira:

PYTHONPATH=`pwd` py.test

Ou uma terceira solução dada pelo @rochacbruno : 

python -m pytest tests/

:+1:
